schedule:
  second-day: WEDNESDAY
  max-per-week: 2

voting:
  min-ready: 4

spawn:
  world: world
  min-distance: 1000
  max-distance: 8000
  max-attempts: 120
  lenient-after: 80

event:
  duration-minutes: 60

combat:
  respawn-lock-minutes: 10

boss:
  behavior:
    leash-radius: 50
    aoe-radius: 8
    aoe-damage: 6
    minions-per-wave: 2
    temp-block-ttl-seconds: 20

bosses:
  next-type: zombie
  zombie:
    health: 600
    allowed-biomes:
      - "!*_OCEAN"
      - "!RIVER"
  fire:
    health: 600
    allowed-biomes:
      - DESERT
      - BADLANDS
      - ERODED_BADLANDS
      - WOODED_BADLANDS

rewards:
  money: 50

loot-tables:
  zombie:
    rolls: 2
    entries:
      - material: DIAMOND
        weight: 70
        amount:
          min: 1
          max: 2
        metadata:
          name: "&bОсколок титана"
          lore:
            - "&7Добыча с мирового босса"
            - "&8Тип: ZOMBIE"
        flags:
          - HIDE_ATTRIBUTES
      - material: EMERALD
        weight: 30
        amount:
          min: 3
          max: 6
        metadata:
          name: "&aИзумрудный клад"
        unique:
          event-item: true

  fire:
    rolls: 2
    entries:
      - material: BLAZE_ROD
        weight: 65
        amount:
          min: 1
          max: 3
        metadata:
          name: "&6Огненный жезл"
          lore:
            - "&7Трофей с огненного босса"
        flags:
          - HIDE_ATTRIBUTES
      - material: MAGMA_CREAM
        weight: 35
        amount:
          min: 2
          max: 5
        unique:
          event-item: true
