schedule:
  second-day: WEDNESDAY
  max-per-week: 2

voting:
  min-ready: 4

spawn:
  world: world
  min-distance: 1000
  max-distance: 8000
  max-attempts: 120
  lenient-after: 80

event:
  duration-minutes: 60

combat:
  respawn-lock-minutes: 10
  respawn-lock:
    waiting-world: world_waiting
    kick-if-waiting-world-missing: true

boss:
  behavior:
    leash-radius: 50

bosses:
  next-type: zombie_giant
  zombie_giant:
    health: 1200
    reward-coins-min: 50
    reward-coins-max: 70
    allowed-biomes:
      - PLAINS
      - FOREST
      - TAIGA
      - SAVANNA
  ifrit_titan:
    health: 500
    reward-coins-min: 60
    reward-coins-max: 80
    allowed-biomes:
      - DESERT
      - BADLANDS
      - ERODED_BADLANDS
      - WOODED_BADLANDS
  raid_archmage:
    health: 650
    reward-coins-min: 60
    reward-coins-max: 60
    allowed-biomes:
      - PLAINS
      - FOREST
      - DARK_FOREST
  giant_phantom:
    health: 800
    reward-coins-min: 50
    reward-coins-max: 50
    allowed-biomes:
      - "!*_OCEAN"
      - "!RIVER"
  giant_shulker:
    health: 850
    reward-coins-min: 70
    reward-coins-max: 70
    allowed-biomes:
      - "!*_OCEAN"
      - "!RIVER"
  forest_guardian:
    health: 1100
    reward-coins-min: 0
    reward-coins-max: 0
    allowed-biomes:
      - FOREST
      - BIRCH_FOREST
      - JUNGLE

  fire:
    rolls: 2
    entries:
      - material: BLAZE_ROD
        weight: 65
        amount:
          min: 1
          max: 3
        metadata:
          name: "&6Огненный жезл"
          lore:
            - "&7Трофей с огненного босса"
        flags:
          - HIDE_ATTRIBUTES
      - material: MAGMA_CREAM
        weight: 35
        amount:
          min: 2
          max: 5
        unique:
          event-item: true
